### ISSUE TITLE
[Bug]: CHANNEL chat_id not support bigint

### ISSUE THREAD

**Issue by lostsnow** [PaiGramTeam/PaiGram#742]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

7eee4fa29d407f3e7eccdd005c5f4b93840f362b

### 运行环境

Ubuntu

### 运行架构

AMD64

### 重现步骤

Set CHANNEL in `.env`:

```
CHANNELS=[{ "name": "Genshin Prime", "chat_id": -1001622600000 }]
```

chat_id is a negative bigint

### 期望的结果是什么？

no error

### 实际的结果是什么？

```
paigram-paimon-1  | Traceback (most recent call last):
paigram-paimon-1  |   File "/app/venv/bin/alembic", line 8, in <module>
paigram-paimon-1  |     sys.exit(main())
paigram-paimon-1  |              ^^^^^^
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/config.py", line 641, in main
paigram-paimon-1  |     CommandLine(prog=prog).main(argv=argv)
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/config.py", line 631, in main
paigram-paimon-1  |     self.run_cmd(cfg, options)
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/config.py", line 608, in run_cmd
paigram-paimon-1  |     fn(
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
paigram-paimon-1  |     script.run_env()
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
paigram-paimon-1  |     util.load_python_file(self.dir, "env.py")
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
paigram-paimon-1  |     module = load_module_py(module_id, path)
paigram-paimon-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
paigram-paimon-1  |     spec.loader.exec_module(module)  # type: ignore
paigram-paimon-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paigram-paimon-1  |   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
paigram-paimon-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
paigram-paimon-1  |   File "/app/alembic/env.py", line 14, in <module>
paigram-paimon-1  |     from core.config import config as application_config
paigram-paimon-1  |   File "/app/core/config.py", line 1, in <module>
paigram-paimon-1  |     from gram_core.config import ApplicationConfig, config, JoinGroups
paigram-paimon-1  |   File "/app/gram_core/config.py", line 166, in <module>
paigram-paimon-1  |     config = ApplicationConfig()
paigram-paimon-1  |              ^^^^^^^^^^^^^^^^^^^
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/env_settings.py", line 40, in __init__
paigram-paimon-1  |     super().__init__(
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
paigram-paimon-1  |     raise validation_error
paigram-paimon-1  | pydantic.error_wrappers.ValidationError: 1 validation error for ApplicationConfig
paigram-paimon-1  | channels -> 0
paigram-paimon-1  |   value is not a valid integer (type=type_error.integer)
paigram-paimon-1 exited with code 0
```

**Comment by omg-xtao** [comment]
`CHANNELS=[-1001622600000]`

**Comment by lostsnow** [comment]
Wiki https://github.com/PaiGramTeam/PaiGram/wiki/Env-Settings#%E6%96%87%E7%AB%A0%E6%8E%A8%E9%80%81%E7%BE%A4%E7%BB%84-%E5%8F%AF%E9%80%89%E9%85%8D%E7%BD%AE%E9%A1%B9 needs to be updated

**Comment by luoshuijs** [comment]
这个验证的问题管理插件很久维护了，不懂能不没运行是个问题，如果有问题请告诉我们
The validation issue management plugin has been maintained for a long time, and if it's not running, we don't understand why. If there are any problems, please let us know.
