### ISSUE TITLE
[Bug]: TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

### ISSUE THREAD

**Issue by lostsnow** [PaiGramTeam/PaiGram#830]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

468b47426247c3e56479e251cad0d79a350d89e9

### 运行环境

Ubuntu

### 运行架构

AMD64

### 重现步骤

```
docker compose build
docker compose up -d
```

### 期望的结果是什么？

No error

### 实际的结果是什么？

```
paigram-paimon-1  | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
paigram-paimon-1  | [INFO  wait] --------------------------------------------------------
paigram-paimon-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
paigram-paimon-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
paigram-paimon-1  | [2024-06-09 20:33:31] INFO     目标进程正在启动                                                                      gram_core.builtins.reloader 162  
paigram-paimon-1  |                       SUCCESS  目标进程启动成功                                                                      gram_core.builtins.reloader 169  
paigram-paimon-1  | Process SpawnProcess-1:
paigram-paimon-1  | Traceback (most recent call last):
paigram-paimon-1  |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
paigram-paimon-1  |     self.run()
paigram-paimon-1  |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
paigram-paimon-1  |     self._target(*self._args, **self._kwargs)
paigram-paimon-1  |   File "/app/run.py", line 15, in run
paigram-paimon-1  |     from core.application import Application
paigram-paimon-1  |   File "/app/core/application.py", line 3, in <module>
paigram-paimon-1  |     from gram_core.application import Application
paigram-paimon-1  |   File "/app/gram_core/application.py", line 12, in <module>
paigram-paimon-1  |     from fastapi import FastAPI
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/fastapi/__init__.py", line 7, in <module>
paigram-paimon-1  |     from .applications import FastAPI as FastAPI
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/fastapi/applications.py", line 16, in <module>
paigram-paimon-1  |     from fastapi import routing
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/fastapi/routing.py", line 22, in <module>
paigram-paimon-1  |     from fastapi import params
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/fastapi/params.py", line 5, in <module>
paigram-paimon-1  |     from fastapi.openapi.models import Example
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/fastapi/openapi/models.py", line 124, in <module>
paigram-paimon-1  |     class Schema(BaseModelWithConfig):
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
paigram-paimon-1  |     cls.__try_update_forward_refs__()
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/main.py", line 807, in __try_update_forward_refs__
paigram-paimon-1  |     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
paigram-paimon-1  |     update_field_forward_refs(f, globalns=globalns, localns=localns)
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
paigram-paimon-1  |     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
paigram-paimon-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paigram-paimon-1  |   File "/app/venv/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
paigram-paimon-1  |     return cast(Any, type_)._evaluate(globalns, localns, set())
paigram-paimon-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paigram-paimon-1  | TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

**Comment by lostsnow** [comment]
https://github.com/pydantic/pydantic-core/issues/1292

**Comment by omg-xtao** [comment]
Pydantic solved issue three hours ago, but has yet to release a new version; here is a temporary workaround: Change  `FROM python:3.12-bookworm` to `FROM python:3.12.2-bookworm` in the Dockerfile.
